version: "3.8"
services:
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis

